-- Drop old table if exists
DROP TABLE IF EXISTS analytics_data;

-- Create individual product tables with daily metrics

-- Toner Pads 1 Pack
CREATE TABLE IF NOT EXISTS toner_1pack_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL UNIQUE,
  gmv DECIMAL,
  items_sold INTEGER,
  orders INTEGER,
  aov DECIMAL,
  units_per_order DECIMAL,
  product_impressions BIGINT,
  page_views INTEGER,
  click_through_rate DECIMAL,
  visitors INTEGER,
  customers INTEGER,
  conversion_rate DECIMAL,
  dollar_per_visitor DECIMAL,
  dollar_per_customer DECIMAL,
  subscribers INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_toner_1pack_date ON toner_1pack_daily(date DESC);

-- Toner Pads 2 Pack
CREATE TABLE IF NOT EXISTS toner_2pack_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL UNIQUE,
  gmv DECIMAL,
  items_sold INTEGER,
  orders INTEGER,
  aov DECIMAL,
  units_per_order DECIMAL,
  product_impressions BIGINT,
  page_views INTEGER,
  click_through_rate DECIMAL,
  visitors INTEGER,
  customers INTEGER,
  conversion_rate DECIMAL,
  dollar_per_visitor DECIMAL,
  dollar_per_customer DECIMAL,
  subscribers INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_toner_2pack_date ON toner_2pack_daily(date DESC);

-- Toner Pads 3 Pack
CREATE TABLE IF NOT EXISTS toner_3pack_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL UNIQUE,
  gmv DECIMAL,
  items_sold INTEGER,
  orders INTEGER,
  aov DECIMAL,
  units_per_order DECIMAL,
  product_impressions BIGINT,
  page_views INTEGER,
  click_through_rate DECIMAL,
  visitors INTEGER,
  customers INTEGER,
  conversion_rate DECIMAL,
  dollar_per_visitor DECIMAL,
  dollar_per_customer DECIMAL,
  subscribers INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_toner_3pack_date ON toner_3pack_daily(date DESC);

-- NAD+ Cream
CREATE TABLE IF NOT EXISTS nad_cream_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL UNIQUE,
  gmv DECIMAL,
  items_sold INTEGER,
  orders INTEGER,
  aov DECIMAL,
  units_per_order DECIMAL,
  product_impressions BIGINT,
  page_views INTEGER,
  click_through_rate DECIMAL,
  visitors INTEGER,
  customers INTEGER,
  conversion_rate DECIMAL,
  dollar_per_visitor DECIMAL,
  dollar_per_customer DECIMAL,
  subscribers INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_nad_cream_date ON nad_cream_daily(date DESC);

-- Toner & NAD+ Bundle
CREATE TABLE IF NOT EXISTS toner_nad_bundle_daily (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL UNIQUE,
  gmv DECIMAL,
  items_sold INTEGER,
  orders INTEGER,
  aov DECIMAL,
  units_per_order DECIMAL,
  product_impressions BIGINT,
  page_views INTEGER,
  click_through_rate DECIMAL,
  visitors INTEGER,
  customers INTEGER,
  conversion_rate DECIMAL,
  dollar_per_visitor DECIMAL,
  dollar_per_customer DECIMAL,
  subscribers INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_toner_nad_bundle_date ON toner_nad_bundle_daily(date DESC);

-- Enable Row Level Security
ALTER TABLE toner_1pack_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE toner_2pack_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE toner_3pack_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE nad_cream_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE toner_nad_bundle_daily ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated access
CREATE POLICY "Allow all operations for authenticated users" ON toner_1pack_daily FOR ALL USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON toner_2pack_daily FOR ALL USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON toner_3pack_daily FOR ALL USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON nad_cream_daily FOR ALL USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON toner_nad_bundle_daily FOR ALL USING (true);
